import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>MY projects</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">My Projects!</a>
				</h1>

				<div className={styles.grid}>
					<a href="/apicrud" className={styles.card}>
						<h2>API CRUD Projects &rarr;</h2>
						<p>I created this using mock api with axios</p>
					</a>

					<a href="/localcrud" className={styles.card}>
						<h2>Localstorage CRUD &rarr;</h2>
						<p>I created this using loacal storage with storeJS library</p>
					</a>
					<a href="/crudOperation" className={styles.card}>
						<h2>Redux CRUD &rarr;</h2>
						<p>I created this using redux and middlewares</p>
					</a>
				</div>
			</main>
		</div>
	);
}
